### ISSUE TITLE
Update reference to upstream tuning profiles

### ISSUE THREAD

**Issue by sthirugn** [RedHatSatellite/satellite6-performance-tuning#14]
For Satellite 6.7 and above, [update this part of tuning doc](https://github.com/RedHatSatellite/satellite6-performance-tuning/blob/051ad1b677b96e23716ed00c1633de3cfcc1a4fb/docs/system-requirements.rst#quick-tuning-guide) to point to [6.7 predefined tuning docs](https://access.redhat.com/documentation/en-us/red_hat_satellite/6.7/html/installing_satellite_server_from_a_connected_network/performing_additional_configuration_on_satellite_server#tuning-satellite-server-with-predefined-profiles) rather than reference to [upstream tuning profiles](https://github.com/RedHatSatellite/satellite-support/tree/master/tuning-profiles)

**Comment by psuriset** [comment]
@Imaanpreet

**Comment by sthirugn** [comment]
thank you, @jhutar
