### ISSUE TITLE
semaphores count tuning for very big satellites

### ISSUE THREAD

**Issue by jhutar** [RedHatSatellite/satellite6-performance-tuning#22]
Hello @Imaanpreet . Another idea forwarded by @pmoravec from email `Satellite default kernel values in /etc/sysctl.conf that require tuning and are NOT present in the documentation for tuning Satellite-6.7`

See https://access.redhat.com/solutions/4783401

**Comment by pmoravec** [comment]
This evolved in a kernel problem that does not release unused semaphores and semaphore arrays in some scenarios.

I think this issue can be closed, then.

**Comment by jhutar** [comment]
Thank you!
