### ISSUE TITLE
outdated link in docs/satellite-configuration-tuning.rst

### ISSUE THREAD

**Issue by jhutar** [RedHatSatellite/satellite6-performance-tuning#25]
Hello Imaan. This link leads to 404 page only now. Also it refers to Sat 6.7:

https://access.redhat.com/documentation/en-us/red_hat_satellite/6.7/html/installing_satellite_server_from_a_connected_network/preparing_your_environment_for_installation#hardware_storage_prerequisites

**Comment by Imaanpreet** [comment]
Hello, it's already resolved in the current tuning guide branch `devel`. So, closing this issue.
