### ISSUE TITLE
Typo in puma tuning in Sat tuning guide

### ISSUE THREAD

**Issue by Imaanpreet** [RedHatSatellite/satellite6-performance-tuning#29]
there is some confusion in Puma tuning in

https://access.redhat.com/sites/default/files/attachments/performance_tuning_for_red_hat_satellite_6.9_0.pdf

(in https://access.redhat.com/solutions/5996891)

that refers to puma options

--foreman-service-puma-threads-min
--foreman-service-puma-threads-max
--foreman-service-puma-workers

While they should be:

--foreman-foreman-service-puma-threads-min
--foreman-foreman-service-puma-threads-max
--foreman-foreman-service-puma-workers

See satellite-installer --help | grep puma.

Also, it would be great if you can clarify that these options are satellite-installer ones (somebody asked me where to find it in foreman-maintain).

I understand that adding the extra "foreman-" to the table can overlap the cells, though.

**Comment by Imaanpreet** [comment]
@pmoravec , Hello I have created the issue here. Will keep you updated.

**Comment by Imaanpreet** [comment]
Hello, @pmoravec 

`satellite-installer --full-help | grep puma
                                  the value of $foreman_service_puma_threads_max is used if it's higher than $db_pool. (current: 5)
    --foreman-foreman-service-puma-threads-max  Maximum number of threads for Puma. Relevant only when Puma service is used and ignored when Passenger is used. (current: 16)
    --reset-foreman-foreman-service-puma-threads-max Reset foreman_service_puma_threads_max to the default value (16)
    --foreman-foreman-service-puma-threads-min  Minimum number of threads for Puma. Relevant only when Puma service is used and ignored when Passenger is used. (current: 0)
    --reset-foreman-foreman-service-puma-threads-min Reset foreman_service_puma_threads_min to the default value (0)
    --foreman-foreman-service-puma-workers  Number of workers for Puma. Relevant only when Puma service is used and ignored when Passenger is used. (current: 2)
    --reset-foreman-foreman-service-puma-workers Reset foreman_service_puma_workers to the default value (2)
`

we need to update the following : 

1. --foreman-foreman-service-puma-threads-min
2. --foreman-foreman-service-puma-threads-max
3. --foreman-foreman-service-puma-workers

Tested the puma testing with above options only, you are right it's a typo. Thank you for bringing this up. 

It's resolved now. 

Updated PDF - https://access.redhat.com/sites/default/files/attachments/performance_tuning_for_red_hat_satellite_6.91.pdf
Updated KCS - https://access.redhat.com/solutions/5996891

**Comment by Imaanpreet** [comment]
Hello, as we already updated the changes so closing this issue. Please re-open it if we missed any thing. Thank you.

**Comment by jhutar** [comment]
Hello @Imaanpreet . Should this be changed in these tables in https://redhatsatellite.github.io/satellite-performance-tuning/#threads-min-effects as well?

**Comment by Imaanpreet** [comment]
Hello @jhutar , I have fixed the typos in these tables as well. Ref - https://github.com/RedHatSatellite/satellite-performance-tuning/blob/devel/docs/satellite-configuration-tuning.rst#threads-min-effects
