### ISSUE TITLE
For devel/6.10 branch can we drop chapter about MongoDB?

### ISSUE THREAD

**Issue by jhutar** [RedHatSatellite/satellite6-performance-tuning#31]

**Comment by Imaanpreet** [comment]
Yes, we don't have it. We have pulp core db which is in postgres.  

Will remove MongoDB in 6.10 branch.

**Comment by jhutar** [comment]
I still see lots of references to MongoDB and whole chapter about it: e.g. https://redhatsatellite.github.io/satellite-performance-tuning/#mongodb-tuning

**Comment by Imaanpreet** [comment]
Hello, we dropped a chapter about MongoDB in Sat 6.10/devel branch.
