### ISSUE TITLE
No db-pool information in recommendations (5.3.5)

### ISSUE THREAD

**Issue by waldirio** [RedHatSatellite/satellite6-performance-tuning#35]
Hello,

In `5.3.5 Recommendations` I can see `Recommended Puma Threads` and `Recommended Puma Workers` for different scenarios, which is really great. However, I have a question that I would like to share.

Normally, via `satellite-installer` we can pass the flags below in order to set the values
```
    --foreman-db-pool ??
    --foreman-foreman-service-puma-threads-max ??
    --foreman-foreman-service-puma-threads-min ??
    --foreman-foreman-service-puma-workers ??
```

It's not clear in the doc two points

1. `Recommended Puma Threads` should be informed in `puma-threads-max` and `puma-threads-min`?
2. What is the recommended value to `db-pool` on each scenario? I believe the value should change as well according to the # of Content Hosts.

Thank you
Waldirio

**Comment by wbclark** [comment]
hi @waldirio , great question.

the effective value of `$db_pool` will be automatically set to equal `$foreman::foreman_service_puma_threads_max`

actually, it will be the maximum of `$foreman::db_pool` and `$foreman::foreman_service_puma_threads_max` but both have default value 5, so any increase to the max threads above 5 will automatically increase the database connection pool by the same amount

for details of how that is implemented, see: https://github.com/theforeman/puppet-foreman/commit/026d47434316b8ae318c5e42936edc12859ab475

**Comment by jhutar** [comment]
AI:
* Change heading "Recommended Puma Threads" to state it is for both min and max
* Add details on how db_pool is determined as wbclark noted ^^^

**Comment by Imaanpreet** [comment]
@jhutar : Above mentioned points has been implemented. 

Thank you @waldirio .
